# Generated by Django 6.0.4 on 2026-04-30 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_place_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='occupancyhistory',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
